### ISSUE TITLE
Add support for secp256k1 public key recovery.

### ISSUE THREAD

**Issue by hazae41** [Zoltu/ethereum-crypto#1]
I want to verify a signed message, given the message, the signature and an Ethereum address.
However, the `verify` function only accepts public keys, and I can't convert an address to a public key.

How can I do that? 

Thanks.

**Comment by MicahZoltu** [comment]
This library doesn't currently support public key recovery, which is what you need (given a signature and a message, recover the public key).  That being said, you are the second person who has wanted this (the first being me), so I'm going to leave this issue open as a feature request.

**Comment by hazae41** [comment]
Okay, thanks

**Comment by MicahZoltu** [comment]
This feature is added in v2.2.2, along with a couple minor (very unlikely to be reached) bugs.
